server:
  port: 8081
#spring.mustache.suffix=.html
spring:
    
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist, classpath:/templates
  mvc:
    view:
      suffix: .html
  # jpa properties
  # SQL문 정렬하여 출력 
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
  sql:
    init:
      platform: postgres